### ISSUE TITLE
Use GitBook instead of WeChat

### ISSUE THREAD

**Issue by kmahyyg** [sunym1993/flash-linux0.11-talk#18]
As far as I know, WeChat MP platform link is not always available and has difficult to be collected into favorites folder.

Why not switch to GitBook?

**Comment by kmahyyg** [comment]
By the way, starred. Thanks for your hard work.

**Comment by xushunke** [comment]
可能微信流量更赚钱也更容易推广吧

**Comment by xiaotianZhang456** [comment]
不太理解你的话，微信在中国是最流行的社交软件之一，微信公众号平台依托与微信，很容易收藏，在中国的话，链接总是可以打开，gitbook并不是大家都在用，但是微信基本上每个人都在用

**Comment by kmahyyg** [comment]
gitbook 不是大家都在用？ 真是笑死我了。

难道你不用浏览器？微信不是所有人都在用，但浏览器一定是。

**Comment by xiaotianZhang456** [comment]
?搁这偷换概念呢， gitbook等于浏览器吗，好好笑

**Comment by kmahyyg** [comment]
> ?搁这偷换概念呢， gitbook等于浏览器吗，好好笑

原来你不用浏览器访问gitbook网页啊

**Comment by honeyeyo** [comment]
gitbook在国内访问缓慢。over！

**Comment by muyiyangyang** [comment]
你好，你的邮件已收到，谢谢！

**Comment by fishman0131** [comment]
您好，邮件已收到，我会尽快查阅。

**Comment by muyiyangyang** [comment]
你好，你的邮件已收到，谢谢！

**Comment by fishman0131** [comment]
您好，邮件已收到，我会尽快查阅。

**Comment by superjcd** [comment]
收到了，谢谢
