### ISSUE TITLE
为何选择0.11版本？

### ISSUE THREAD

**Issue by Firestar-Reimu** [sunym1993/flash-linux0.11-talk#59]
是因为您个人比较熟悉还是这个版本有什么重大突破？

**Comment by wxkskynet** [comment]
难道不是因为越早期的系统越简单吗

**Comment by Firestar-Reimu** [comment]
那总得有个相比于0.10，0.12，1.0之类的早期版本的理由吧？

**Comment by adoyle-h** [comment]
是啊。现在内核版本都到 v6.3-rc1，跟 v0.11 差距太大了。虽说很多操作系统书籍以 v0.11 版本为教材，但还是期望有教材能以围绕 v6 版本讲解。

**Comment by jeason1997** [comment]
> 是啊。现在内核版本都到 v6.3-rc1，跟 v0.11 差距太大了。虽说很多操作系统书籍以 v0.11 版本为教材，但还是期望有教材能围绕 v6 版本讲解。

最新的系统都几千万行代码了吧，而且大部分是驱动。想要讲解感觉会很困难。

**Comment by muyiyangyang** [comment]
你好，你的邮件已收到，谢谢！

**Comment by Toin1779712664** [comment]
这个没法说的呀，要是最新的内核那么学习起来就太臃肿了，最简单的就是学习旧版本边学边改都可以
